version: '2'
services:
  mesin1:
    container_name: progjar-mesin-1
    image: jupyter/scipy-notebook
    user: root
    ports:
      - "60001:8888"
    environment:
      - "DOCKER_STACKS_JUPYTER_CMD=lab"
      - "GRANT_SUDO=yes"
    volumes:
      - ./work:/home/jovyan/work
      - ./script:/script
    command: "sh /script/run.sh"
  mesin2:
    container_name: progjar-mesin-2
    image: jupyter/scipy-notebook
    user: root
    ports:
      - "60002:8888"
    environment:
      - "DOCKER_STACKS_JUPYTER_CMD=lab"
      - "GRANT_SUDO=yes"
    volumes:
      - ./work:/home/jovyan/work
      - ./script:/script
    command: "sh /script/run.sh"
  mesin3:
    container_name: progjar-mesin-3
    image: jupyter/scipy-notebook
    user: root
    ports:
      - "60003:8888"
    environment:
      - "DOCKER_STACKS_JUPYTER_CMD=lab"
      - "GRANT_SUDO=yes"
    volumes:
      - ./work:/home/jovyan/work
      - ./script:/script
    command: "sh /script/run.sh"
  mesin4:
    container_name: progjar-mesin-4
    image: jupyter/scipy-notebook
    user: root
    ports:
      - "60004:8888"
    environment:
      - "DOCKER_STACKS_JUPYTER_CMD=lab"
      - "GRANT_SUDO=yes"
    volumes:
      - ./work:/home/jovyan/work
      - ./script:/script
    command: "sh /script/run.sh"

